<h1>Terms of Service</h1>
<p>Version 1.1</p>
<p>Effective Date: 1st july, 2012</p>
<p>READ THESE TERMS OF USE CAREFULLY BEFORE USING THE SERVICE "CITYAPI" OFFERED BY MATTS' HB (“MATTS'”), A COMPANY IN MALMÖ, SWEDEN. THESE TERMS AND CONDITIONS SET FORTH THE LEGALLY BINDING CONDITIONS FOR YOUR USE OF THE WEBSITE HTTP://CITYAPI.US (THE “SITE”) AND THE SERVICES, FEATURES, FUNCTIONALITY, CONTENT, APPLICATIONS AND WIDGETS OFFERED BY CITYAPI (COLLECTIVELY WITH THE SITE, THE “SERVICE”). If you do not agree to these Terms, you cannot use the Service. Matts' provides the Service subject to your acceptance and ongoing compliance with these Terms.</p>
<p>Matts' reserves the right at its sole discretion to modify these Terms periodically. Matts' will notify you of such changes via an email sent to the email address on file for you or via other notification mechanism. Matts' may require your assent to the modified terms as a condition of your continued access to the Service. Your continued use of the Service after the effective date of such modifications indicates your acceptance to the modified Terms. If you breach any of these Terms, your permission to use the Service and access the Site automatically terminates, unless such breach is waived by Matts' in writing in its sole discretion.</p>
<h2>1. Acceptance of Terms.</h2>
<p>By registering for and/or using the Service in any way, including but not limited to accessing or using the Site, you agree to all the conditions set forth herein (“Terms”), which also includes Matts' privacy policy, or any other operating rules, policies, guidelines and procedures that may be published from time to time on the Site by Matts', each of which is incorporated by reference and each may be updated by Matts' from time to time. In addition, certain services provided through the Service may be subject to additional conditions specified by Matts' from time to time; your use of such services is subject to these additional terms, which are part of these Terms by this reference. These Terms apply to all users of the Service, including, without limitation, users who contribute content, information and other materials or services on the Site, individual users of the Service and corporate entities and venues using the Service.</p>
<h2>2. Access.</h2>
<p>2.1 The Service shall include, but not be limited to, any service Matts's performs, all applications, widgets or versions offered by Matts' that you download from the Site or third-party stores (e.g., the Apple iTunes Store, Blackberry App World, SpotifyApps or Google Play) authorized by Matts', as well as the offering of materials displayed or performed on or through the Service (including Content (as defined below)).</p>
<p>2.2 You acknowledge that use of the Service requires connection to, and data transfers over, the network and therefore may impact your data usage charges imposed by your wireless operator or other service provider. It is your responsibility to obtain at your cost all equipment, software and internet access necessary to use the Service.</p>
<h2>3. Registration and Eligibility.</h2>
<p>3.1 You may browse the site and view Content without registering, but as a condition of using some aspects of the Service, you must register with CityAPI. In doing so, you represent, warrant and covenant that you provide Matts' with accurate, truthful and complete registration information (including, but not limited to your name (“User Name”), e-mail address and password that you use to access the Service) and to keep your registration information accurate and up-to-date. Failure to do so shall constitute a violation of these Terms, which may result in immediate termination of your CityAPI account.</p>
<p>3.2 You shall not (a) provide any false personal information to Matts' (including a false user name) or create an account for anyone other than yourself without that person’s permission; (b) use a user name that is the name of another person with the intent to impersonate that person; (c) use a user name or create or use a CityAPI account subject to any rights of a third party without appropriate authorization; or (d) use a user name that is a name that is otherwise offensive, vulgar or obscene or otherwise illegal.</p>
<p>3.3 Matts' reserves the right to refuse to register or cancel any user name at its sole discretion. You are solely responsible for the activity that occurs on your account or under your User Name, and shall be responsible for maintaining the confidentiality of your CityAPI password. You will not use another user’s account without such other user’s express permission. You will immediately notify Matts' in writing of any unauthorized use of your account, or other account-related security breach of which you are or become aware.</p>
<p>3.4 You represent and warrant that if you are an individual, you are of legal age to form a binding contract, or if you use the Service on behalf of an entity, you have the right to enter into and bind the entity to these Terms and to register for the Service. The Service is not available for persons who are under 13 years of age. Matts' may, in its sole discretion, refuse to offer the Service to any person or entity and change its eligibility criteria at any time. You are solely responsible for ensuring that these Terms, and accessing and using the Service, are in accordance with all laws, rules and regulations that apply to you. The right of access to the Service is revoked if these Terms or use of the Service are prohibited, and in such case, you agree not to use or access the Service in any way.</p>
<h2>4. Content.</h2>
<p>4.1 All Content, whether publicly posted or privately transmitted, is the sole responsibility of the person who originated such Content. Matts' does not guarantee the authenticity of any Content that users may provide about themselves. You acknowledge that all use, reproduction and display of all Content is at your own risk and you will be solely responsible for any damage or loss to you or another party arising from such use, reproduction and display of all Content. For the purposes of these Terms, the term “Content”, means, without limitation, any location information, “Projects,” "places," "resources," comments, information, data, text, photographs, software, scripts, graphics and interactive features generated, provided or otherwise made available by Matts' on or through the Service. All Content that is created, uploaded, submitted, distributed or sent into the Service by its users is collectively defined as “User Submissions”.</p>
<p>4.2 Subject to your compliance with these Terms, Matts' grants each user of the Service a worldwide, non-exclusive, non-sublicensable, non-transferable license to use, modify and reproduce the Content, solely for personal, noncommercial use. Use, reproduction, modification, distribution or storage of content for other than personal, noncommercial use is expressly prohibited without the written permission of Matts'. You may not sell, license, rent, or otherwise use or exploit any content for commercial (whether for profit or not) use or in any manner that violates any third party right.</p>
<p>4.3 The Service contains Content specifically provided by Matts' or its affiliates, and such content is protected by copyrights, trademarks, service marks, patents, trade secrets or other proprietary rights and laws, as applicable. You must follow and maintain all copyright notices, information and restrictions contained in any Content accessed through the Service. Matts' retains all right, title and interest in and to the Service, and all associated intellectual property rights. Except as expressly authorized by these Terms, you shall not use, reproduce, or distribute Content. The user interface, user experience, icons, presentation layer and elements, terminology, reports, layouts, and screen displays of or generated by the Service are Matts'’s copyrightable content, trade dress and servicemarks, and shall not be reproduced, distributed, or displayed except for your internal or personal use and not for external use or exploitation.</p>
<h2>5. User Submissions.</h2>
<p>5.1 Matts' may use your User Submissions in a number of ways in connection with the Service and Matts'’s business as Matts' determines in its sole discretion, including but not limited to, publicly displaying, formatting, incorporating into marketing materials, advertisements and other works, creating derivative works from, promoting, and distributing User Submissions, and to allow others to do the same. By submitting User Submissions on the Site or otherwise through the Service, you hereby grant Matts' a worldwide, nonexclusive, royalty-free, perpetual, irrevocable, fully paid right and license to use, copy, edit, modify, distribute, prepare derivative works of, display, perform, and otherwise fully exploit User Submissions in connection with the Service and Matts'’s business (and that of its successors and assigns), including without limitation for promoting and redistributing part or the whole of the Site (and derivative works thereof) or the Service, in any media formats and through any media channels (including, without limitation, third-party sites and feeds). You represent and warrant that you have all rights to grant such a license without infringement or violation of any rights of third parties, including without limitation, privacy rights, publicity rights, copyrights, contract rights or any other intellectual property or proprietary rights.</p>
<p>5.2 You understand that all Content publicly posted or privately transmitted through the Serivce is the sole responsibility of the person from whom the Content originated, that Matts' shall not be held liable for any errors or omissions in any Content, and that Matts' does not guarantee the identity of any other users with whom you interact through the Service.</p>
<p>5.3 When you remove your User Submissions, you understand that copies of User Submissions may persist in backup copies for a reasonable time or may remain with users who earlier have accessed or downloaded your User Submissions.</p>
<h2>6. Rules and Conduct.</h2>
<p>6.1 As a condition of use, you promise not to use the Service for any purpose that is prohibited by these Terms. You are responsible for all your activity in connection with the Service. In addition, you shall abide by all applicable local, state, national and international laws and regulations.</p>
<p>6.2 By way of example, and not as a limitation, you shall not (and do not allow any third party to) upload, download, post, transmit or otherwise distribute or facilitate distribution of any Content on or through the Service, including without limitation any User Submission, that: (a) infringes any patent, trademark, trade secret, copyright, right of publicity or other rights any other person or entity or violate any law or contractual duty; (b) you know is false, deceptive, untrue or incorrect; (c) is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another’s privacy, tortious, obscene, vulgar, pornographic, abusive, profane, contain or depict nudity, contains or depicts sexual activity, promotes bigotry, discrimination or violence or is otherwise inappropriate as determined by Matts' in its sole discretion; (d) constitutes spam or other unauthorized or unsolicited advertising, junk or bulk e-mail; (e) contains viruses or other code, computer files, worms, logic bombs or programs that are designed or intended to disrupt, disable, damage, limit or impair the operation of any computer software or hardware or telecommunications equipment or to damage or obtain unauthorized access to any system, data, password or other information of Matts' or any third party; (f) impersonates any person or entity, including any employee or representative of Matts'; (g) constitutes identification documents or sensitive financial information; or (h) violates the integrity and/or any of the policies and rules that are hereby incorporated, including the Matts' privacy policy.</p>
<p>6.3 To preserve the integrity of the Service, you shall not (directly or indirectly): (a) take steps that lead to or may impose (as determined by the Matts', in its sole discretion) an unreasonable or disproportionately large load on the Matts' (or its third party providers’) infrastructure; (b) interfere or attempt to interfere with the operation of the Service or any activities conducted on the Service; (c) circumvent the measures Matts' may use to prevent or limit access to the Service (or other accounts, computer systems or networks connected to the Service); (d) run any form of auto-responder or “spam” on the Service; (e) use manual or automated software, devices, or other processes to “crawl” or “spider” the Service or any page on the Site; (f) harvest or scrape the Content from the Service; (g) modify, adapt, appropriate, reproduce, distribute, translate, create derivative works or adaptations of, publicly display, publish, reproduce, sell, trade, or otherwise use the Service or the Site Content (other than your own User Submissions), other than expressly authorized by Matts'; (h) decipher, decompile, disassemble, reverse engineer or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Service (including without limitation any application or widget), except to the limited extent applicable laws specifically prohibit such restriction; (i) copy, rent, lease, distribute, or otherwise transfer any of the rights that you receive hereunder; (j) otherwise take any action contrary to Matts' guidelines and policies.</p>
<p>6.4 Matts' does not guarantee that any content or User Submissions (as defined above) will be made available on the Site or through the Service. Matts' has no obligation to monitor the Site, Service, Content or User Submissions. Matts' reserves the right to (a) remove, suspend, edit or modify any Content in its sole discretion, including without limitation any User Submission at any time, without notice and for any reason (including but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content, or if Matts' is concerned that you may have violated these Terms); and (b) remove, disable, or block any User Submission from the Service; and (c) access, read, preserve, and provide any information that Matts' reasonably believes is necessary to (i) satisfy any applicable law, legal process or governmental request, (ii) enforce these Terms of Use, including investigation of potential violations hereof, (iii) detect, prevent or otherwise address fraud, security or technical issues, (iv) respond to user support requests, or (v) protect the rights, property or safety Matts', its users and the public.</p>
<h2>7. Feedback.</h2>
<p>You agree that Matts' is free to use and implement in perpetuity without compensation, attribution or obligation to you any feedback, benchmarks, requirements, suggestions, criticisms, improvements, recommendations, ideas, and error corrections provided by you to us relating to the Service or Content.</p>
<h2>8. Third Party Services and Sites.</h2>
<p>Matts', the Service, other users, or a third party may provide links to other websites or login access via such links. . Such links, sites and services (“Third Party Functions”) shall not be construed as an endorsement, sponsorship, or affiliation. Matts' exercises no control whatsoever over Third Party Functions and are not responsible or liable for the availability thereof or the content, advertising, products or other materials thereon. Matts' shall not be responsible or liable, directly or indirectly, for any damage or loss incurred or suffered by you or any user in connection with Third Party Functions or such Third Party Functions’ availability or lack thereof. Your access and use of Third Party Functions, including information, material, products and services therein, is solely at your own risk.</p>
<h2>9. Termination.</h2>
<p>Matts' may terminate your access to all or any part of the Service, with or without cause, with or without notice, effective immediately, which could lead to forfeiture and destruction of Your User Submissions, Content, personalization settings and all tasks associated with the Service. If you want to terminate your account, you may do so by following the instructions on the Site.</p>
<h2>10. Warranty Disclaimers.</h2>
<p>10.1 Except to the extent required by law, Matts' has no special relationship with or fiduciary duty to you. You acknowledge that Matts' has no control over, and no obligation to take any action regarding, which users gain access to the Service, the Content, what effects the Content may have on you, how you may interpret or use the Content, or what actions you can take as a result of being exposed to the Content.</p>
<p>10.2 You release Matts' from and waive all liability for you having acquired or not acquired Content through the Service. The Service may contain or refer you to sites containing information that some may find offensive or inappropriate. Matts' makes no representations about any Content, and Matts' will not be responsible for the accuracy, completeness, efficacy, copyright compliance, legality or decency of material contained in or accessed through the Service.</p>
<p>10.3 You release Matts' from any liability with respect to your connections and relationships with other users. You understand that Matts' does not in any way screen users, nor does Matts' investigate the backgrounds of users, or attempt to confirm their background or statements. Matts' makes no representations or warranties regarding the conduct or statements of other users, or the veracity of information users provide. Under no circumstances shall Matts' be liable for any damages whatsoever, whether direct, indirect, general, special, compensatory, consequential, and/or incidental, arising out of or in connection with the Service, or relating to conduct by you or anyone else in connection with the Service, including without limitation, bodily injury, emotional suffering, and all damages arising in any way from communications or meetings with people that you meet or interact through the Service. You agree to take reasonable precautions and exercise the utmost care in all interactions with any person with whom you come in contact through the Service. Additionally, Matts' makes no warranty that (a) the Service will meet your requirements, goals or needs, (b) Service access will be uninterrupted, timely, secure or error-free, or (c) any errors or deficiencies will be corrected. Further, scheduled and preventive maintenance as well as required and emergency maintenance work may temporarily interrupt access to the Service.</p>
<p>10.4 THE SITE, SERVICE, AND CONTENT ARE PROVIDED “AS IS”, “AS AVAILABLE” AND WITHOUT REPRESENTATION OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF TITLE, NONINFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE OR USAGE OF TRADE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED, SAVE TO THE EXTENT REQUIRED BY LAW.</p>
<p>10.5 Matts' AND ITS DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES, SUPPLIERS, PARTNERS AND CONTENT PROVIDERS DO NOT WARRANT THAT: (A) THE SERVICE WILL BE SECURE OR AVAILABLE AT A CERTAIN TIME OR LOCATION, (B) ANY DEFECTS OR ERRORS WILL BE CORRECTED, (C) ANY CONTENT OR SOFTWARE AVAILABLE AT OR VIA THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR (D) THE RESULTS OF USING THE SERVICE WILL MEET YOUR REQUIREMENTS. YOUR USE OF THE WEBSITE, SERVICE, AND CONTENT IS AT YOUR OWN RISK. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
<p>10.6 Because no online system is perfectly secure or reliable, the internet is an inherently insecure medium, and the reliability of hosting services, internet intermediaries, your internet service provider, and other service providers cannot be assured, you accept security and other risks associated with or arising from your use of the Service, and the responsibility for choosing to use a technology that does not provide perfect security or reliability.</p>
<h2>11. Indemnification.</h2>
<p>11.1 You shall defend, indemnify and hold harmless Matts', its affiliates and each of its, and its affiliates’ employees, agents, contractors, directors, suppliers and representatives (“Protected Parties”) from all losses, costs, actions, claims, damages, expenses (including reasonable legal costs) or liabilities, that arise from or relate to your use or misuse of, or access to, the Site, Service, Content, or from your User Submissions, violation of these Terms, or violation by you or any third party using your account, of any intellectual property or other right to any person or entity (except to the extent that a court of competent jurisdiction rules that such a claim was caused by an act or omission of Matts'). Matts' reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which case you will assist and cooperate with Matts' in asserting any available defenses. Further, in the event you have a dispute with one or more users, you hereby release the Protected Parties from claims, demands and damages (actual, direct and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, foreseeable and unforeseeable, arising out of or in any way connected with such disputes.</p>
<p>11.2 FOR CALIFORNIA RESIDENTS: You further agree that these Terms waive and release any claims that would otherwise be preserved by operation of section 1542 of the California Civil Code, which provides, “A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which if known by him or her must have materially affected his or her settlement with the debtor.” You understand that you are releasing the Protected Parties from all claims, whether known or unknown to you, and whether or not you suspect that those claims may exist at this time.</p>
<h2>12. Limitation of Liability.</h2>
<p>12.1 ALL RESPONSIBILITY OF Matts', ITS DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES, PARTNERS, SUPPLIERS OR CONTENT PROVIDERS HOWSOEVER ARISING FROM ANY LOSS SUFFERED AS A RESULT OF YOUR USE OF THE SITE, SERVICE, CONTENT, AND USER SUBMISSIONS, IS EXPRESSLY EXCLUDED TO THE FULLEST EXTENT PERMITTED BY LAW, SAVE THAT IF A COURT OF COMPETENT JURISDICTION DETERMINES THAT THE LIABILITY OF Matts', ITS DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES, PARTNERS, SUPPLIERS OR CONTENT PROVIDERS (AS APPLICABLE) HAS ARISEN, THE TOTAL OF SUCH LIABILITY SHALL BE LIMITED IN AGGREGATE TO TWENTY US DOLLARS ($20).</p>
<p>12.2 To the maximum extent permitted by applicable law, in no event shall Matts', its directors, employees, agents, representatives, partners, suppliers or content providers, be liable under contract, tort, strict liability, negligence or any other legal or equitable theory or otherwise (and whether or not Matts', its directors, employees, agents, representatives, partners, suppliers or content providers had prior knowledge of the circumstances that lead to such loss or damage) with respect to the Site, Service, Content, and User Submissions for: (a) indirect or consequential losses or damages; (b) loss of actual or anticipated profits, value, revenue, goodwill, data, or savings; (c) wasted expenditures; or (d) cost of procurement of substitute goods or services.</p>
<p>12.3 Matts' will not be held responsible for any violation of local law, be it zoning, property based, developmental or otherwise.  You and you alone are responsible for proposals and projects carried out using CityAPI and you agree to ensure that such proposals and projects fully comply with all local laws, regulations and ordinances.  Further, if you fail to do so, Matts' reserves the right to terminate your account on CityAPI and any other services.</p>
<p>12.4 Applicable law may not allow the limitation or exclusion of liability or incidental or consequential damages, so the above limitation or exclusion may not apply to you. In such case, Matts'’s liability will be limited to the fullest extent permitted by applicable law.</p>
<h2>13. Trademarks.</h2>
<p>You are granted no right, title or license to any third party trademarks by these Terms, or to any of Matts' trademarks or servicemarks. Matts' reserves all right, title and interest in and to Matts'’s trademarks, servicemarks, trade names, domain names, and similar identifiers, including CityAPITM and Matts'TM (“Marks”).  You shall not: (a) challenge Matts'’s ownership or use of the Marks; (b) attempt to register any Marks; or (c) incorporate any Marks into your trademarks, service marks, company names, Internet addresses, domain names, or any other similar designations. Any and all use of the Marks by or for you inures to Matts' benefit.  If you acquire any rights in any Marks by operation of law or otherwise, you will immediately and at no expense to Matts', assign such rights to Matts' along with any associated goodwill, applications and registrations.</p>
<h2>14. US DMCA.</h2>
<p>If you believe that your property has been affected by a user of the Site in a way that breaks local laws or ordinances, you may notify Matts' by providing Matts' with the following<br>
a) identification of the property that you claim has been affected;<br>
b) identification of the actors and actions that is claimed to be acting illegally and information reasonably sufficient to permit us to investigate the incidence;<br>
c) your name, address, telephone number, and email address;<br>
d) a statement by you that you have a good faith belief that the disputed use is not authorized by the owner, governing body of jurisdiction or the law; and<br>
e) a statement, made under penalty of perjury, that the above information in your notice is accurate and that you are the  owner or are authorized to act on the owner’s behalf.<br>
The above writing must be electronically or physically signed by you. If Matts' receives such a claim, Matts' may refuse or delete Content as described under this section, or terminate a user’s account in accordance with these Terms. Matts' contact information can be found on the CityAPI web page.  In addition to forwarding your notice to the person who provided the allegedly illegal Content, Matts' may send a copy of your notice  to other agents deemed necessary to assist in assessing the legal claims. Matts' reserves the right to remove Content alleged to be infringing or otherwise illegal without prior notice and in Matts' sole discretion. In appropriate circumstances, Matts' may also terminate your account if you are determined to be a repeat infringer.
<h2>15. Governing Law.</h2>
<p>These Terms, the Service, the Site and Content, and any disputes related to or concerning any of the foregoing (including tort as well as contract claims, and whether pre-contractual or extra-contractual) shall be governed by the laws of Sweden. The choice of law rules of any jurisdiction shall not apply and shall not be invoked in any proceeding between the parties. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to these Terms, the Service, the Site or Content must be filed within one year after such claim or cause of action arose, or be forever barred.</p>
<h2>16. Dispute Resolution.</h2>
<p>Any disputes between or claims brought by you or us arising out of or related to these Terms, the Service, the Site or Content (including tort as well as contract claims, and whether pre-contractual or extra-contractual, as well as the arbitrability of any disputes) shall be referred to and finally settled by binding arbitration before the International Court of Arbitration in accordance with the Rules of Arbitration of the International Chamber of Commerce (“ICC”) in effect at the time of arbitration except as inconsistent with this section. The arbitration shall be conducted by telephone, on-line and/or based solely upon written submissions where no in-person appearance is required. If in-person appearance is required, such hearings shall be held in Malmö, Sweden. The arbitrator shall apply the law specified in section 15 above. All awards may if necessary be enforced by any court having jurisdiction. The existence of any dispute, the existence or details of the arbitration proceeding, and all related documents, materials, evidence, judgments and awards therein, shall be kept confidential. Except as required by law, no party shall make any public announcements with respect to the proceeding or the award, except as required to enforce same. You and Matts' agree that by agreeing to these Terms, the parties hereby waive the right to a trial by jury and agree to only bring claims in an individual capacity and not as a plaintiff or class member in any purported class or representative proceeding.  Notwithstanding the foregoing, nothing in this section shall preclude the right and ability to file and maintain at any time an action for recovery of injunctive or provisional relief in any court of competent jurisdiction under the laws applicable thereto. All claims (excluding requests for injunctive or equitable relief) between the parties must be resolved using arbitration in accordance with this section. Should either party file an action contrary to this section, the other party may recover lawyers’ fees and costs, provided that the party seeking the award has notified the other party in writing of the improperly filed claim, and the other party has failed to withdraw the claim in a timely manner.</p>
<h2>17. Assignment.</h2>
<p>These Terms shall not be assigned, delegated, or transferred by you, in whole or in part, whether voluntarily, involuntarily, by merger, consolidation, dissolution, sale of assets, or otherwise, without Matts'’s prior written consent. Any such purported assignment, delegation or transfer without such written consent shall be void. Matts' may at any time assign these Terms without prior consent or notice, providing that your rights under these Terms are not prejudiced. These Terms shall be binding on, and inure to the benefit of, the parties and their respective and permitted successors and assigns.</p>
<h2>18. Injunctive Relief.</h2>
<p>You acknowledge and agree that breach of these Terms, or any unauthorized use, disclosure or distribution of the Content, may cause irreparable harm to Matts', the extent of which would be difficult to ascertain, and that Matts' shall be entitled to seek immediate injunctive relief (in addition to any other available remedies), in any court of competent jurisdiction under the applicable laws thereto.</p>
<h2>19. Miscellaneous.</h2>
<p>19.1 The Terms constitute the entire agreement between you and Matts', and supersede any prior agreements. If any provision of the Terms is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and that the other provisions of the Terms remain in full force and effect.</p>
<p>19.2 No waiver of any provision of these Terms shall be deemed a further waiver or continuing waiver of such provision or any other provision, and Matts' failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. Nothing herein shall be deemed to create an agency, partnership, joint venture, employee-employer or franchisor-franchisee relationship of any kind between Matts' and any user or other person or entity, nor do these terms extend rights to any third party.</p>
<p>19.3 If you believe that you are entitled or obligated to act contrary to these Terms under any mandatory or applicable law, you agree to provide Matts' with detailed and substantiated explanation of your reasons in writing at least thirty days before you so act, to allow Matts' to assess whether Matts' may, at its sole discretion, provide an alternative remedy for the situation, though Matts' is under no obligation to do so.</p>
<p>19.4 For purposes of service messages and notices about the Service to you, Matts' may place a banner notice across Site pages or other medium to alert you to certain changes such as modifications to these Terms. Alternatively, notice may consist of an email from Matts' to an email address associated with your account, even if Matts' has other contact information. You also agree that Matts' may communicate with you in relation to your account and otherwise in relation to these Terms through your account or through other contact information you have provided, including email, mobile number, telephone, or delivery services including the postal service. You acknowledge and agree that Matts' shall have no liability associated with or arising from your failure to maintain accurate contact or other information, including, but not limited to, your failure to receive critical information about the Service. You agree that all agreements, notices, disclosures and other communications to you electronically satisfy any legal requirement that such communications be in writing.</p>
<p>19.5 The Service is controlled by Matts' from its offices in Sweden. Matts' makes no representation that any of the Service or Content are appropriate for use in other jurisdictions. Your use of or access to the Service shall not be construed as Matts'’s purposefully availing itself of the benefits or privileges of doing business in any state or jurisdiction other than Sweden.</p>
<p>19.6  In the event that this Agreement is translated into other languages and there is a discrepancy between the two language versions, the English language version shall prevail to the extent that such discrepancy is the result of an error in translation.</p>
<h2>End of Terms</h2>
